include!(concat!(env!("OUT_DIR"), "/fixtures_macro.rs"));

macro_rules! generate_fixture_test {
    ($fixture_name:expr) => {
        paste::paste! {
            #[test]
            fn [<test_fixture_ $fixture_name>]() {
                let content = include_str!(concat!("../../web/fixtures/", $fixture_name, ".liquid"));

                crate::assert_json_output!(content);
            }
        }
    };
}

// This macro is generated by the build script and will iterate over all files in the /web/fixtures directory
// and generate a test for each.
for_each_fixture_file!(generate_fixture_test);
