[package]
name = "liquid_doc_parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
pest = "2.7"
pest_derive = "2.7"

[dev-dependencies]
insta.workspace = true
paste = "1.0"
pretty_assertions.workspace = true
