[package]
name = "liquid_doc_core"
version = "0.1.0"
edition = "2021"
authors = ["Guilherme Carreiro <guilherme.carreiro@shopify.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
